# --- THIS IS THE FIX ---
# Update the apiVersion to match the GKE-managed driver
apiVersion: secrets.gke.io/v1
# ---------------------
kind: SecretProviderClass
metadata:
  name: auth-redis-secrets
spec:
  provider: gcp
  parameters:
    # This is your Project ID
    projectID: {{ .Values.global.projectId }}
    secrets:
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/redis-host/versions/latest"
        path: "redis-host" # The file name this will create in /mnt/secrets/
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/redis-port/versions/latest"
        path: "redis-port" # The file name this will create in /mnt/secrets/
