apiVersion: v1alpha1 # This is the specific API version for the GKE-managed driver
kind: SecretProviderClass
metadata:
  name: auth-redis-secrets
spec:
  driver: gcp-secret-manager # FIX: Use the correct GKE-managed driver name
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/redis-host/versions/latest"
        fileName: "redis-host"
      - resourceName: "projects/{{ .Values.global.projectId }}/secrets/redis-port/versions/latest"
        fileName: "redis-port"